---
title: "chap_9"
author: "linhnm"
date: "5/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

ex turbines
```{r}
data("turbines"); str(turbines)

tur.m1 <- glm(Fissures / Turbines ~ Hours, weights = Turbines, data = turbines, family = binomial())
tur.m2 <- update(tur.m1, family = binomial(link = "probit"))
tur.m3 <- update(tur.m1, family = binomial(link = "cloglog"))

summary(tur.m1)
```

compare 3 link func
```{r}

tr.array <- rbind(coef(tur.m1), coef(tur.m2), coef(tur.m3))
tr.array <- cbind(tr.array, c(deviance(tur.m1), deviance(tur.m2), deviance(tur.m3)))

colnames(tr.array) = c("Intercept", "Hours", "Residual deviation")
rownames(tr.array) = c("Logit", "Probit", "C log-log")

tr.array

#summary(tur.m1)
```

goodness of fit test for deviance
```{r}
resQ <- qresid(tur.m1)
qqnorm(resQ)
qqline(resQ)

```
calculate ED50
```{r}
library("MASS")
ED50 <- cbind("logit" = dose.p(tur.m1), "probit" = dose.p(tur.m2), "c-log-log" = dose.p(tur.m3))
ED50
```
check lack of fit
```{r}
c(Df = df.residual(tur.m1), Resid.Dev = deviance(tur.m1), pearson.x2 = sum(resid(tur.m1, type = "pearson")^2))
```
wald test
```{r}
wald.test(Sigma = vcov(tur.m1), b = coef(tur.m1), Tearms = c(1))
```



ex germ
```{r}
data("germ"); str(germ)

fit <- glm(Germ / Total ~ Extract * Seeds, weights = Total, data = germ, family = binomial(link = "logit"))
summary(fit)
wald.test(Sigma = vcov(fit), b = coef(fit), Terms = 1:3)
confint(fit)

-0.4122 - qnorm(0.975) * 0.1842
-0.4122 + qnorm(0.975) * 0.1842

dose.p(fit)
#exp(coef(fit))
```

pr 9.6

```{r}
betaM <- c(0.45, 0.04, 0.25, 0.23)
seM <- c(0.4, 0.08, 0.15, 0.17)
betaF <- c(-0.22, 0.26, 0.82, -0.22)
seF <- c(0.53, 0.06, 0.19, 0.11)
zM <- betaM / seM
zF <- betaF / seF
pvalM <- (1 - pnorm(abs(zM))) * 2
pvalF <- (1 - pnorm(abs(zF))) * 2

cbind("male beta" = betaM, "male p-value" = pvalM)
cbind("female beta" = betaF, "female p-value" = pvalF)
```
```{r}
# 95% confidence interval for beta
betaM.l <- betaM - qnorm(0.975) * seM
betaM.u <- betaM + qnorm(0.975) * seM
cbind("lower beta" = betaM.l, "mean beta" = betaM, "upper beta" = betaM.u)
```
calculate for overdispersion
```{r}
nMale <- 1323; nFemale <- 1427
pMale <- 13; pFemale <- 13
DfMale <- nMale - pMale
DfFemale <- nFemale - pFemale


```

ex 9.7
```{r}
data("shuttles"); str(shuttles)
shuttles
fit <- glm(Damaged / 6 ~ Temp, weights = rep(6, length(Temp)), data = shuttles, family = binomial())
summary(fit)

fit$null.deviance - fit$deviance
pchisq(fit$null.deviance - fit$deviance, 1, lower.tail = FALSE)

mu <- predict(fit, newdata = data.frame(Temp = 31), se.fit = TRUE, type = "response")
mu

dose.p(fit)
```
solve
```{r}
library(statmod)
data(shuttles)
### Part 1
plot( Damaged/6 ~ Temp, data=shuttles)
### Part 2
shuttle.m <- glm(Damaged/6 ~ Temp, weights=rep(6, length(Temp)),
family=binomial, data=shuttles)
### Part 3
qqnorm( qresid(shuttle.m))
qqline(qresid(shuttle.m))
colSums(influence.measures(shuttle.m)$is.inf)
### Part 4
predict(shuttle.m, newdata=data.frame(Temp=31), type="response")
```

ex 9.8
```{r}
df <- data.frame("Dose" = c(0.000625, 0.00125, 0.0025, 0.005, 0.01),
                 "Total" = rep(40, 5),
                 "Survivors" = c(7, 18, 32, 35, 38))
df

fit <- glm(Survivors / Total ~ 1 + log(Dose), weights = Total, data = df, family = binomial())

summary(fit)

# likelihood ratio test
pchisq(fit$null.deviance - fit$deviance, 1, lower.tail = FALSE)

# plot data with fitted model
plot(1 + log(df$Dose), log(df$Survivors/df$Total / (1 - df$Survivors/df$Total)),
     xlab = "Dose func",
     ylab = "Survivor logit",
     xlim = c(-7, -3),
     ylim = c(-2, 4))
lines(1 + log(df$Dose), 11.2375 + 1.7094 * (log(df$Dose)),
     xlim = c(-7, -3),
     ylim = c(-2, 4))

#ED50
ed50 <- dose.p(fit)
dose.ed50 <- exp(ed50) # with dose = does.ed50, 50% numbers of mice are survival

```
ex 9.9
```{r}
data("budworm"); str(budworm)
length(budworm$Killed)
bud.m = budworm[budworm$Gender == "M", ]
bud.f = budworm[budworm$Gender == "F", ]
par(mfrow = c(1, 2))
plot(bud.m$Dose, bud.m$Killed/bud.m$Number)
plot(bud.f$Dose, bud.f$Killed/bud.f$Number)
```
```{r}
# fit the model
fit <- glm(Killed/Number ~ 1 + log2(Dose) * Gender, weights = Number, data = budworm, family = binomial())
#summary(fit)
anova(fit, test = "Chisq")

fitG <- glm(Killed/Number ~ 1 + log2(Dose) + Gender, weights = Number, data = budworm, family = binomial())
summary(fitG)

anova(fitG, test = "Chisq")
```
```{r}
# plot fitted line
par(mfrow = c(1, 2))
plot(1 + log2(bud.m$Dose), log(bud.m$Killed/bud.m$Number / (1 - bud.m$Killed/bud.m$Number)),
     xlab = "male log dose",
     ylab = "male logit", 
     xlim = c(0, 6),
     ylim = c(-4, 3))
lines(1 + log2(bud.m$Dose), -3.4732 + 1.0642 * log2(bud.m$Dose) + 1.1007,
      xlim = c(0, 6),
      ylim = c(-4, 3))

plot(1 + log2(bud.f$Dose), log(bud.f$Killed/bud.f$Number / (1 - bud.f$Killed/bud.f$Number)),
     xlab = "female log dose",
     ylab = "female logit", 
     xlim = c(0, 6),
     ylim = c(-4, 3))
lines(1 + log2(bud.f$Dose), -3.4732 + 1.0642 * log2(bud.f$Dose),
      xlim = c(0, 6),
      ylim = c(-4, 3))

title("fitted model for male and female")

```

```{r}
# xap xi yen ngua va goodness of fit test
min(bud.m$Killed)
min(bud.f$Killed)

# likelihood ratio test
pchisq(fitG$null.deviance - fitG$deviance, fitG$df.null - fitG$df.residual, lower.tail = FALSE)
```
```{r}
# estimate ed50
summary(fitG)
ld50.f <- dose.p(fitG, c(1, 3))
ld50.m <- dose.p(fitG, c(2, 3))
exp(c(ld50.f, ld50.m))

3.4732 / 1.0642
(-3.4732 + 1.1007) / 1.0642

fitG$coefficients

exp(fitG$coefficients[["log2(Dose)"]])
```
```{r}
fitM <- glm(Killed/Number ~ 1 + log2(Dose), weights = Number, data = bud.m, family = binomial())
fitF <- glm(Killed/Number ~ 1 + log2(Dose), weights = Number, data = bud.f, family = binomial())

summary(fitM)
summary(fitF)
```
```{r}
# confint 90% of beta
confint(fitG, level = 0.9)
```


