---
title: "chap_8"
author: "linhnm"
date: '2022-05-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

pr 8.4
```{r}
set.seed(10)
y <- rpois(1000, 1)
mean(y)
hist(y)
#y
fit <- glm(y ~ 1, family = poisson(link = "log"))
fit$coefficients

resD <- resid(fit)
resP <- resid(fit, type = "pearson")
resQ <- qresid(fit)

rs1 <- sum(fit$weights * fit$residuals^2)
rs2 <- sum(resP^2)
rs3 <- sum(resD^2)

summary(fit)

# goodness of fit test
1 - pchisq(rs2, df = 0)
pchisq(c(1, 2, 10, 100, 300), df = 10)

#qqnorm(resD)
#qqline(resD)
#title("q-q plot for deviance residual")

#qqnorm(resP)
#qqline(resP)
#title("q-q plot for pearson residual")

#qqnorm(resQ)
#qqline(resQ)
#title("q-q plot for quantile residual")

```

pr 8.10
```{r}
data("seabirds"); str(seabirds)
fit <- glm(Count ~ Quadrat + factor(Species), data = seabirds, family = poisson(link = "log"))
fit

resD <- resid(fit)
resP <- resid(fit, type = "pearson")
resQ <- qresid(fit)
f <- fitted(fit)
plot(f, resQ)

1 - pchisq(c(fit$deviance, sum(resP^2)), df = 1)

qqnorm(resQ)
qqline(resQ)
```

```{r}
y <- c(15, 26, 4); x <- c(1/4, 1/2, 1/4)
fit <- glm( y ~ 0+x, family=poisson)
summary(fit)
pearson.gof <- sum(fit$weights * fit$residuals^2)
resPearson <- resid(fit, type = "pearson")
1 - pchisq(sum(resPearson^2), df = 2)
1 - pchisq(fit$deviance, df = 2)
```

pr 8.11
```{r}
data("blocks"); str(blocks)
hist(blocks$Number)

set.seed(100)
lambda <- mean(blocks$Number)
y <- rpois(1000, lambda)
hist(y)

m1 <- glm(Number ~ Age, data = blocks, family = poisson())
summary(m1)

#plot(rstandard(m1)~fitted(m1))

#rstandard(m1)
#resid(m1)

resP <- resid(m1, type = "pearson")
resQ <- qresid(m1)

qqnorm(resQ)
qqline(resQ)

summary(aov(m1))

m1$df.residual
length(blocks$Number)

pchisq(c(m1$deviance, sum(resQ^2)), df = m1$df.residual, lower.tail = FALSE)

```

